### PR TITLE
ART: Fix a few issues around lower bound / erase

### LINKED ISSUE #559: roaring64: and_inplace gives incorrect value
This is with all outstanding roaring64 PRs included.

Reproduction:
```c
uint64_t start = 0x0FFFF;
uint64_t end = 0x20001;

roaring64_bitmap_t* r1 = roaring64_bitmap_from_range(start, end, 1);
roaring64_bitmap_add(r1, 0xFFFF0000);

roaring64_bitmap_t* r2 = roaring64_bitmap_from_range(start, end, 1);

uint64_t and_cardinality = roaring64_bitmap_and_cardinality(r1, r2);
assert_int_equal(and_cardinality, end - start);

roaring64_bitmap_t* r3 = roaring64_bitmap_and(r1, r2);
assert_int_equal(roaring64_bitmap_get_cardinality(r3), and_cardinality);

roaring64_bitmap_and_inplace(r1, r2);
assert_int_equal(roaring64_bitmap_get_cardinality(r1), and_cardinality); // This line fails, `0x10001 != 0x10002`
assert_true(roaring64_bitmap_equals(r1, r3));

roaring64_bitmap_free(r1);
roaring64_bitmap_free(r2);
roaring64_bitmap_free(r3);
```

### PR DESCRIPTION
**Pull request by SLieve**
Fixes #559 

1. Leaf keys were written to the wrong location: `memcpy(&leaf->key` instead of `memcpy(leaf->key`
2. In `art_node_iterator_lower_bound`, we did not check if the key chunk for the lower bound child was greater than the key chunk we searched for.
3. In `art_iterator_erase` there were a few issues that would lead to an incorrect location. I've somewhat sidestepped the most tricky bit by doing a lower bound search from the root instead.

Added tests for 1 and 2. Also slightly improved `art_printf` for debugging.

### CODE REVIEW

**Comment by Dr-Emann** [comment]
Think the change to `art_node_iterator_lower_bound` made for a possible infinite loop:

```c
roaring64_bitmap_t* r1 = roaring64_bitmap_create();
roaring64_bitmap_add(r1, 829185);
roaring64_bitmap_t* r2 = roaring64_bitmap_create();
roaring64_bitmap_add(r2, 0);
roaring64_bitmap_add(r2, 14418687);

roaring64_bitmap_and_cardinality(r1, r2); // This function never returns

roaring64_bitmap_free(r1);
roaring64_bitmap_free(r2);
```

It appears this function call doesn't actually move the iterator at all in this case: https://github.com/RoaringBitmap/CRoaring/blob/4a7474e81351ece3c3be80445793746997a0dded/src/roaring64.c#L823

**Comment by SLieve** [comment]
Should be fixed with my latest commit. I aim to improve the test coverage to catch issues like these in the future.

**Review by Dr-Emann — APPROVED** [review]

**Review by Dr-Emann — CHANGES_REQUESTED** [review]
```c
roaring64_bitmap_t *r1 = roaring64_bitmap_of(2, 0x000001, 0xFFFFF0001);
roaring64_bitmap_t *r2 = roaring64_bitmap_of(2, 0x100001, 0xFFFFF0001);

uint64_t card = roaring64_bitmap_and_cardinality(r1, r2);
assert_int_equal(card, 1); // This assert fails: `0 != 1`

roaring64_bitmap_free(r1);
roaring64_bitmap_free(r2);
```

**Comment by SLieve** [comment]
Should be fixed with the latest commit.

**Review by Dr-Emann — APPROVED** [review]

**Pull request merged**
