### PR TITLE
Apply clang-format

### PR DESCRIPTION
**Pull request by olan-ibm**
Applying `clang-format` ahead of custom memory management pull request to eliminate style diffs as discussed [here](https://groups.google.com/g/roaring-bitmaps/c/zGRJ8IXuLoU/m/4eylrUDvCAAJ).

Version used: `6.0.0-1ubuntu2`

### CODE REVIEW

**Comment by olan-ibm** [comment]
I am still verifying that this solution will help with the merge process of my other PR. I would hold of on merging this until I have finished verifying.

**Comment by lemire** [comment]
You can probably ignore the failing test.

**Comment by olan-ibm** [comment]
I was able to revert the `clang-format` changes in my branch, so this PR is no longer needed.

**Comment by lemire** [comment]
How did you do that? (I am curious.)

**Comment by olan-ibm** [comment]
Manually, unfortunately. Side by side diffs with `v0.2.66` (the base branch) and a few hours.

I attempted to merge my changes against a formatted version of `master` as proposed, but this lead to an insurmountable number of conflicts as Git considered both sides of the merge as changed.

I was able to merge up my isolated changes to `master` yesterday. I am just awaiting final internal clearances to stage my changes.

**Comment by lemire** [comment]
> Manually, unfortunately.

To be clear, I was more than willing to avoid you this pain.

**Comment by olan-ibm** [comment]
Ultimately the pain was caused by my own carelessness with `clang-format`. I appreciate how accommodating you have been during this process :-)

I tried the method discussed in the Google Group locally by formatting the master branch to match my changes and attempted to merge, but since my branch was also out of date (based on tag `v0.2.66`) so this ended up being even more difficult.

**Pull request closed without merging**
