### PR TITLE
This makes the C++ somewhat more strict.

### PR DESCRIPTION
**Pull request by lemire**
For folks using -Weffc++ and cppcheck.

### CODE REVIEW

**Comment by AE1020** [comment]
Mostly harmless...but...applying some peer pressure to the people requesting it, to rethink their priorities would seem preferable.  🤷‍♂️

**Comment by lemire** [comment]
> applying some peer pressure to the people requesting it, to rethink their priorities would seem preferable.

Do you see harm?

**Comment by AE1020** [comment]
The empty constructor is the kind of thing you'd see someone (like me) casually edit out without thinking, so motivating why it's there would be good:

    Roaring()
         : roaring{}  // silence -Weffc++
    {
        api::roaring_bitmap_init_cleared(&roaring);
    }

> Notice how I did not include it in our build setup.

So long as it's being catered to, it's best to turn the warning on for at least one mostly-empty C++ test file (maybe the one done from amalgamation.sh, since it's public-facing already?).  That would make sure that the basic inclusion of the header doesn't trip it, without holding any of the other test files to the rule.

**Comment by lemire** [comment]
I did add explicit comments to explain the empty constructors.

**Pull request merged**
