### PR TITLE
add avx512 support

### PR DESCRIPTION
**Pull request by lemire**
I just did some minor tweaks but no actual difficult work. 

Built on top of https://github.com/RoaringBitmap/CRoaring/pull/446

Work by hui han([hui.han@intel.com](mailto:hui.han@intel.com))
Signed-off-by: lifan lin([lifan.lin@intel.com](mailto:lifan.lin@intel.com))

### CODE REVIEW

**Comment by huihan365** [comment]
> @huihan365 Would you review?

Yes,  I have review the codes and there is no comments from my side, thanks for your patient work.

**Comment by lemire** [comment]
@Dr-Emann Want to take a look?

**Comment by lemire** [comment]
@huihan365 Thanks. We will be merging this 'soon'. :-)

**Comment by Dr-Emann** [comment]
Honestly simd stuff isn't super in my wheelhouse yet, so my eyes glazed over for a lot of it, but I didn't see anything wrong.

**Pull request merged**
