### PR TITLE
Implement shift operations

### PR DESCRIPTION
**Pull request by Oppen**
For #186 and #144.
It's still a work in progress. It's close to finished but I still need to sort out some bugs in the bitset implementation and clean up the tests, which are currently a bit of a mess and don't really convey enough information on failure.

UPDATE: ready for review.

### CODE REVIEW

**Comment by Oppen** [comment]
Ignore the poor commit messages. I intend on rebasing after I'm done with this.

**Comment by lemire** [comment]
@Oppen This fails our unit tests, right?

**Comment by Oppen** [comment]
Interestingly enough, it worked locally, and yet there's a typo in the tests that understandably breaks it. I'm pushing a fix now.

**Comment by Oppen** [comment]
Besides some other assertion failing, I noticed MSVC isn't too happy about how we vendor cmocka. Is it a good idea to make a more traditional vendoring by copying the whole sources to that subdir?
I need a specific feature from 1.1.x for the tests to not become huge and complicated (the ability to pass an initial state, so I can more easily share code between cases).

**Comment by Oppen** [comment]
Or, alternatively, is it an option to make it into a dependency? Maybe adding a check to CMakeLists?

**Comment by lemire** [comment]
@Oppen I am not sure why you can't just update cmocka. I have not investigated your troubles though.

Copying the files in the project is not ideal. It is possible to have CMake recover the version we need...

https://github.com/simdjson/simdjson/blob/95b4870e20be5f97d9dcf63b23b1c6f520c366c1/dependencies/import.cmake#L6-L35

It is a balancing act. If the dependency is tiny, and if it changes very rarely, a hard copy is fine. If we start updating it, or if it gets to be large, then we want dynamic download... which adds complexity of its own... but is ultimately (at scale) the right choice.

**Comment by Oppen** [comment]
> @Oppen I am not sure why you can't just update cmocka. I have not investigated your troubles though.
> 
I did, but the way I did fails on MSVC apparently.

> Copying the files in the project is not ideal. It is possible to have CMake recover the version we need...
> 
> https://github.com/simdjson/simdjson/blob/95b4870e20be5f97d9dcf63b23b1c6f520c366c1/dependencies/import.cmake#L6-L35
> 
I'll look into this.

> It is a balancing act. If the dependency is tiny, and if it changes very rarely, a hard copy is fine. If we start updating it, or if it gets to be large, then we want dynamic download... which adds complexity of its own... but is ultimately (at scale) the right choice.
It does change very rarely and the code itself isn't very big. However, there's a bunch of CMake modules it adds for proper configuration, and it seems skipping it is less than ideal here.

I like the idea of dynamic download mostly so we don't have to carry ad-hoc changes, but maybe it'd make sense to do that as a separate PR and rebase this after it's merged. Does that sound good?

**Comment by lemire** [comment]
> I like the idea of dynamic download mostly so we don't have to carry ad-hoc changes, but maybe it'd make sense to do that as a separate PR and rebase this after it's merged. Does that sound good?

Small PRs are better.

**Comment by Oppen** [comment]
I rebased against #333.
AppVeyor is taking its time to run there and I wanted to be ready in case it's mergeable, but that needs to be reviewed first.

**Comment by Oppen** [comment]
Rebased against master with dynamically downloaded cmocka.

**Comment by lemire** [comment]
Looks good to me. I like how extensive the tests are.

**Comment by Oppen** [comment]
@lemire shall I merge this?

**Comment by lemire** [comment]
Please do.

**Comment by Ezibenroc** [comment]
@Oppen I started to work on some tests for this function and found two minor issues.

- In my tests, I was surprised to see that an offset of 2^50 did not produce an empty bitmap. Maybe such absurdly high (or low) numbers are not expected by the function, but in this case I think this should be stated more explicitly.
On the other hand, it would be straightforward to check at the beginning of `roaring_bitmap_add_offset` if `offset` is in the appropriate range and return an empty bitmap otherwise.

- The resulting bitmap always has *copy on write* disabled, even if the input bitmap had *copy on write* enabled. I think this should not be the case.

**Comment by Oppen** [comment]
> * In my tests, I was surprised to see that an offset of 2^50 did not produce an empty bitmap. Maybe such absurdly high (or low) numbers are not expected by the function, but in this case I think this should be stated more explicitly.
>   On the other hand, it would be straightforward to check at the beginning of `roaring_bitmap_add_offset` if `offset` is in the appropriate range and return an empty bitmap otherwise.
> 
Yes, the intent was to return an empty bitmap in those cases. It must have been an oversight on my part after I did some simplifying of my original implementation, which was kind of a mess. I'll fix it later today or maybe tomorrow, thanks for the heads up.

> * The resulting bitmap always has _copy on write_ disabled, even if the input bitmap had _copy on write_ enabled. I think this should not be the case.
>
That makes sense. I preferred to keep it simple, but I guess it's only a matter of adding a loop at the end to make them CoW, it shouldn't be too complex.

**Comment by Oppen** [comment]
I guess the case of the non-empty bitmap on huge (or tiny) offsets is probably an integer overflow that I missed, but I'll check later.

**Pull request merged**
