### PR TITLE
Testing amalgamation files

### PR DESCRIPTION
**Pull request by lemire**
This new test will build the amalgamation files and try to execute them, as part of our tests.

### CODE REVIEW

**Comment by Dr-Emann** [comment]
Ah, inlining differences by having all the functions in the same translation unit might be the difference? That makes some sense (and maybe we could also reproduce by using LTO then?).

**Comment by lemire** [comment]
@Dr-Emann That is indeed the idea. I meant to write to you about it, but I had meetings.

**Comment by Dr-Emann** [comment]
No problem. I've been finding some very interesting stuff over at https://github.com/RoaringBitmap/croaring-rs/pull/128#issuecomment-1910991355

TL;DR looking more and more like a compiler bug to me.

**Comment by lemire** [comment]
@Dr-Emann For obvious reasons, I will complete this PR. Testing the amalgamated files is a good idea. And it is cheap.

**Pull request merged**
