### PR TITLE
optimize roaring_bitmap_statistics (breaking change)

### PR DESCRIPTION
**Pull request by AviAvni**
implement https://github.com/RoaringBitmap/CRoaring/issues/619

### CODE REVIEW

**Comment by AviAvni** [comment]
@Dr-Emann ping

**Comment by lemire** [comment]
Looks good to me. It is a breaking change, but one that should be fine.

**Review by lemire — APPROVED** [review]

**Comment by lemire** [comment]
Feedback invited!!!

**Review by Dr-Emann — APPROVED** [review]
LGTM

@lemire do you have a place to keep track of "things to change next major version"? Removing the sum field entirely seems like a good thing to do next major version bump.

**Comment by lemire** [comment]
> do you have a place to keep track of "things to change next major version"? Removing the sum field entirely seems like a good thing to do next major version bump.

I would propose just doing a major version *now*, and indicating this breaking change.

If there is general agreement, I would just do it as simply as that.

I am not aware of any other breaking change, are you?

I mean, we *added* many things, but it would be the first time we remove some functionality in a long time.

**Comment by lemire** [comment]
I am going to merge and issue a *major* version.

**Pull request merged**
