### PR TITLE
fix the 'false' with logical and bug.

### PR DESCRIPTION
**Pull request by hurricane1026**
false && everything == false, so false -> true.

### CODE REVIEW

**Comment by lemire** [comment]
Can you propose a test to verify the fix?

**Comment by hurricane1026** [comment]
> Can you propose a test to verify the fix?
ok, I will write a test case and push to this PR

**Comment by hurricane1026** [comment]
@lemire hi, I add 4 test cases for the fixing.
but 1 on of them failed. It met a internal bug of roaring lib. I debug it and found:
a double free exception occurs in "void shared_container_free(shared_container_t *container)"

**Comment by lemire** [comment]
There seems to be an issue exposed by the roaring64 test you added.

**Comment by hurricane1026** [comment]
@lemire I opened a issue in here [Issue 220](https://github.com/RoaringBitmap/CRoaring/issues/220)

**Comment by hurricane1026** [comment]
@lemire I thought my PR seems no buggy, so merged my PR, then fix the issue 220 will be better?

**Comment by lemire** [comment]
I need to first understand the bug you have exposed. 

I don’t understand it right now and I am away so I can’t investigate right now. I will in the near future, however.

**Comment by lemire** [comment]
Hopefully, this will be fine now. I have isolated and fixed the issue exposed here in master.

**Pull request merged**
