### PR TITLE
Actually perform bitset-bitset ixor in place

### LINKED ISSUE #328: Optimize ixor
Interesting optimization...

https://github.com/RoaringBitmap/RoaringBitmap/pull/542/files

by @richardstartin

### PR DESCRIPTION
**Pull request by Oppen**
This should also fix #328 (thus the branch name).

### CODE REVIEW

**Comment by lemire** [comment]
Looks good. Merging.

**Comment by richardstartin** [comment]
I’m not sure this applies the optimisation in the issue (fission of xor and popcount) which isn’t to say this optimisation is effective in C but it would be interesting to find out…

**Comment by lemire** [comment]
@richardstartin I have re-opened the issue. You are right. Thanks for catching this, I had not actually taken the time to refer back to the issue.

**Comment by Oppen** [comment]
> I’m not sure this applies the optimisation in the issue (fission of xor and popcount) which isn’t to say this optimisation is effective in C but it would be interesting to find out…

Isn't the change actually the opposite? [The commit](https://github.com/RoaringBitmap/RoaringBitmap/pull/542/files) changes from making a popcount first to determine whether to allocate an array and then computing the xor again in-situ when it doesn't to just computing the xor first, the cardinality on the result and only then deciding based on that computation whether it needs to convert to an array.
`bitset_container_xor` computes the xor to the `dst` bitmap and returns the cardinality of the result, which we use to decide whether to convert it to an array.
What am I missing?

**Comment by lemire** [comment]
@Oppen 

I have reclosed 328 because it seems likely that you have captured all of the benefits. The code path is different though it is semantically equivalent. As @richardstartin hinted, we have to deal with distinct programming languages and we cannot apply exactly the same 'optimizations'.

Note that your work is very good.

**Pull request merged**
