### PR TITLE
Dynamically download cmocka

### PR DESCRIPTION
**Pull request by Oppen**
- Add function for importing dependencies from URL
- Convert cmocka to downloaded dep
- Update cmocka to 1.1.5

### CODE REVIEW

**Comment by data-man** [comment]
Is there a reason not to use CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html)?

**Comment by Oppen** [comment]
> Is there a reason not to use CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html)?

There's a reason I didn't: I didn't know it existed. I based the changes on [this module from simdjson](https://github.com/simdjson/simdjson/blob/95b4870e20be5f97d9dcf63b23b1c6f520c366c1/dependencies/import.cmake#L6-L35) under suggestion of @lemire. Which, now that I think of it, I need to attribute somehow. Advice on how is welcome.

There's also a reason I'd wait for more feedback before changing it to use it: the documentation states that's new for CMake 3.11, and the currently minimum version is 2.8, so we should agree to bump that first. I'm unsure whether the pipeline instances can upgrade to 3.11 as well.

@lemire what do you think of this? It does seem like a better way to do it.

**Comment by Oppen** [comment]
I wrote an alternative version based on #334 in case that one's preferred.

**Comment by data-man** [comment]
If you don't want to update CMake, you can check the CMake version in CMakeList.txt and use the previous cmocka installation method for older CMake.

**Comment by Oppen** [comment]
> If you don't want to update CMake, you can check the CMake version in CMakeList.txt and use the previous cmocka installation method for older CMake.

Wouldn't keeping both versions defeat the point of using the new feature?

**Comment by data-man** [comment]
Something like this:
```cmake
if(CMAKE_VERSION VERSION_GREATER 3.10)
   include(FetchContent)
endif()
```
And so on.

**Comment by data-man** [comment]
Just for note: [repology/cmake/versions](https://repology.org/project/cmake/versions).

**Comment by Oppen** [comment]
I understand how that works. But the deps are needed regardless of CMake version, so keeping it compatible with older versions means keeping both implementations (the one based on FetchContent and the one based on the custom module). That would make having a FetchContent path redundant.

**Comment by Oppen** [comment]
The alternative would be to always disable tests for older CMake versions, but I don't think that's desirable.

**Comment by lemire** [comment]
@Oppen @data-man  

The custom approach, though less flexible, can have significant performance benefits over FetchContent. To learn more about our analysis, please review this PR https://github.com/simdjson/simdjson/pull/1258

**Comment by lemire** [comment]
@Oppen You can credit @friendlyanon  who came up with this CMake module, I believe.

**Comment by lemire** [comment]
What you did looks fine. I would merge it if you'd like.

Using fetchcontent is also fine, but may not be strictly better. There is nothing wrong about the approach you have taken. It will work.

**Comment by Oppen** [comment]
Which would be a better way? Just a comment at the top of the source file? Something like:
```
Modified version of https://github.com/simdjson/simdjson/blob/master/dependencies/import.cmake by @friendlyanon
```
Does it need a license header?

Or maybe just mention it in the commit message?

**Comment by Oppen** [comment]
> What you did looks fine. I would merge it if you'd like.
> 
> Using fetchcontent is also fine, but may not be strictly better. There is nothing wrong about the approach you have taken. It will work.

Then I think I'd rather have this one merged. If there are performance benefits and it avoids the need for forcing CMake upgrades on users, I think it's worth it. I can close the other PR then.

**Comment by Oppen** [comment]
But let's figure out how we wish to put credit where it's due first.

**Comment by lemire** [comment]
I think it would be fair to add a comment in the CMake file crediting @friendlyanon as you did. It causes no harm and it credits the original author. As far as licensing issues go, it would implicitly leverage the simdjson license (Apache, https://github.com/simdjson/simdjson/blob/master/LICENSE), so we are good (CRoaring is already under Apache).

**Comment by Oppen** [comment]
Cool, I'll add that and then I'll consider it ready for merge. I'll rebase #331 and close #334 afterwards.

**Comment by Oppen** [comment]
Done.

**Comment by lemire** [comment]
That looks very good to me. If you are happy, let us merge.

**Comment by friendlyanon** [comment]
To be frank, nowadays I would just recommend using vcpkg with overlay ports to import dependencies. You can see an example of that done [here](https://github.com/friendlyanon/cmake-init-vcpkg-example).

If that's something you'd consider, just ping me if there is anything you need help with.

**Comment by lemire** [comment]
@friendlyanon Thank you.

**Pull request merged**
