### PR TITLE
use right value instead of copy value in c++ interface

### PR DESCRIPTION
**Pull request by stdpain**
use move instead of copy in c++ interface which will get good performance under sparse bitmap
https://github.com/StarRocks/starrocks/pull/86

### CODE REVIEW

**Comment by lemire** [comment]
I like it a lot, but I'd like an independent review before merging.

@Oppen would you have a look? It short.

**Comment by Oppen** [comment]
It seems `insert` also implements r-value reference versions, so if `insertOrEmplace` is only for internal use, it may be better to just add an r-value reference version and always use `std::move` in that function. Does that make sense?
I can probably be done that way regardless of it being internal or not, at least Godbolt won't err on a dummy case.

**Comment by stdpain** [comment]
@Oppen  Applied

**Comment by Oppen** [comment]
LGTM!

**Comment by lemire** [comment]
This is nice. Merging.

**Pull request merged**
