### PR TITLE
roaring_bitmap_andnot_nonzero(a,b): check whether `a-b` is nonzero

### PR DESCRIPTION
**Pull request by longqimin**

### CODE REVIEW

**Comment by longqimin** [comment]
i followed the way of `container_intersect`

**Comment by longqimin** [comment]
```
~/s/t/C/build (andnot_nonzero|…) $ ./benchmarks/real_bitmaps_benchmark ../benchmarks/realdata/census1881
x64 processor:  UNKNOWN	 compiler version: 11.2.1 20220127 (Red Hat 11.2.1-9)	AVX2 usable	AVX2 detected	 SSE4.2 detected	 BMI1 detected	 BMI2 detected
Constructing 200  bitmaps.
........................................................................................................................................................................................................
Loaded 200 bitmaps from directory ../benchmarks/realdata/census1881
Creating 200 bitmaps took 19163961 cycles
Copying and freeing 200 bitmaps took 870123 cycles
 199 successive bitmaps intersections took 182721 cycles
 199 successive bitmaps unions took 1833804 cycles
 199 successive in-place bitmaps intersections took 509861 cycles
 199 successive in-place bitmaps unions took 3334109 cycles
Iterating over 200 bitmaps and 1003861 values took 8110928 cycles
 199 successive bitmaps andnot_nonzero took 29468 cycles
 199 successive bitmaps andnot_cardinality took 161160 cycles
```

**Comment by lemire** [comment]
Looks good to me, but I have a small nitpick.

I do not like "andnot_nonzero".

The Java counterpart is clearer...

https://github.com/RoaringBitmap/RoaringBitmap/blob/e2d19edb0b37f5367203126c8b229a1fca2ace69/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L2630-L2655

If you do not like 'contains', we could have `is_subset` or something of the sort.

**Comment by longqimin** [comment]
> Looks good to me, but I have a small nitpick.
> 
> I do not like "andnot_nonzero".
> 
> The Java counterpart is clearer...
> 
> https://github.com/RoaringBitmap/RoaringBitmap/blob/e2d19edb0b37f5367203126c8b229a1fca2ace69/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L2630-L2655
> 
> If you do not like 'contains', we could have `is_subset` or something of the sort.

As you mentioned, “is_subset” is what i want. And we already have “roaring_bitmap_is_subset”, it works the same as i did.

let’s close this.

**Pull request closed without merging**
