### PR TITLE
Fix an issue where uint32 max was ignored in Roaring64Map::flip

### LINKED ISSUE #372: Roaring64Map::flip excludes all uint32 max values
`Roaring64Map::flip` calls `Roaring::flip` like this:

```
            roarings[start_high].flip((std::numeric_limits<uint32_t>::min)(),
                                      (std::numeric_limits<uint32_t>::max)());
```

Since `Roaring::flip` operates on a right-open interval, this results in the max value of each 32-bit roaring to be unaffected.

To reproduce:
```
roaring::Roaring64Map r;
r.add(0ul);
r.add(1ul << 32);
r.flip(0, 1ul << 32);
assert(r.contains((1ul << 32) - 2)); // passes
assert(r.contains((1ul << 32) - 1)); // fails
```

It seems like an easy fix: use uint32 max + 1 instead of uint32 max for the upper bound, as `Roaring::flip` accepts 64-bit values just for this purpose.

### PR DESCRIPTION
**Pull request by SLieve**
Fixes #372. This also adds some unit tests for `Roaring::flip` and `Roaring64::flip`.

### CODE REVIEW

**Comment by SLieve** [comment]
I see that this is also being done in #376. I feel that the additional test cases for flip are useful in any case, as it did not have any tests.

**Comment by lemire** [comment]
> I feel that the additional test cases for flip are useful in any case, as it did not have any tests.

Agreed.

**Comment by lemire** [comment]
I will merge manually the test

**Comment by lemire** [comment]
Merging manually through https://github.com/RoaringBitmap/CRoaring/pull/380 Thanks for the contribution.

**Pull request closed without merging**
