### PR TITLE
Software implementation of popcnt

### PR DESCRIPTION
**Pull request by rodenweller**
POPCNT support was not available on processors until around the time of SSE4.2 instructions. CRoaring flag for SSE4 guarantees POPCNT support. This patch uses that flag to guard against attempted usage
of the popcnt instruction on builds where we have not enabled that level of processor support. A software implentation is provided that should provide good all around performance.

### CODE REVIEW

**Comment by lemire** [comment]
Restarting the build.

**Comment by rodenweller** [comment]
@lemire Thanks, it looks like the checks passed.

**Comment by lemire** [comment]
Indeed.

**Comment by lemire** [comment]
Published as 0.2.56.

**Pull request merged**
