### PR TITLE
Makes helper functions private wrt. translation unit

### PR DESCRIPTION
**Pull request by daniel-j-h**
Hey there :wave: I was reading some code in parallel to the papers and articles and came across a few private functions not marked as such. That's it! Thanks for being amazing and providing not only dope results but also an outstandingly well engineered codebase :raised_hands:

### CODE REVIEW

**Comment by lemire** [comment]
@AE1020 Would you review?

**Comment by AE1020** [comment]
Static limits the visibility so it won't show up in other compilation units, and seems prudent for anything that isn't meant to be called from outside that .c file.  Helps communicate intent if nothing else.

Marking the function inline is likely pointless in a .c file... compiler generally ignores what some people believe to be a human-guided intent regarding optimization.  It is only a linkage instruction ("do not worry about multiple definition"):

https://stackoverflow.com/a/1759575

Some people are bothered by it appearing where it does not apply.

**Comment by lemire** [comment]
@daniel-j-h In light of @AE1020 's comment, would you consider removing the 'inline' qualifier? It seems unwarranted.

I doubt it is harmful, but it could be criticized.

**Comment by daniel-j-h** [comment]
I was following the existing code base like in run.c

https://github.com/RoaringBitmap/CRoaring/blob/master/src/containers/run.c#L777

where static inline is used to semantically mark translation unit local functions private.

I don't really mind having inline there or not, but should we strive for consistency across the code base?

On July 2, 2021 5:05:49 PM UTC, Daniel Lemire ***@***.***> wrote:
***@***.*** In light of @AE1020 's comment, would you consider removing
>the 'inline' qualifier? It seems unwarranted.
>
>I doubt it is harmful, but it could be criticized.

**Comment by lemire** [comment]
Good point. I am merging. We may want to revisit these inline qualifiers later.

**Pull request merged**
