### PR TITLE
Adding macos.

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by lemire** [comment]
I am having trouble reproducing the issue.

**Comment by madebr** [comment]
You can switch between xcode versions using [`xversion select X`](https://github.com/xcpretty/xcode-install).
It's available on the github macos runners: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

**Comment by lemire** [comment]
@madebr The bug is fixed. It was not specific to Apple or LLVM.

**Comment by lemire** [comment]
I am going to issue a patch release in a few minutes.

**Comment by lemire** [comment]
It was a real bug, not a compiler-specific issue.

**Comment by madebr** [comment]
Thanks for the update.
When the version in conan-center-index is updated, please don't forget to update the version in [the conan section of the docs](https://github.com/RoaringBitmap/CRoaring#usage-using-conan) at well.

**Pull request merged**
